In [2]:
from math import e

In [3]:
sigmoid_minus_5 = 1 / (1 + e**-(-5))
sigmoid_minus_5

0.006692850924284857

In [4]:
sigmoid_minus_2_5 = 1 / (1 + e**-(-2.5))
sigmoid_minus_2_5

0.07585818002124356

In [5]:
sigmoid_minus_2_5 = 1 / (1 + e**-(2.5))
sigmoid_minus_2_5

0.9241418199787566

In [6]:
from math import log

In [7]:
log(8, 2)

3.0

In [8]:
log(1000, 10)

2.9999999999999996

In [9]:
import numpy as np
from math import e

In [10]:
X = np.array([160, 170, 180, 190])
X

array([160, 170, 180, 190])

In [11]:
y = np.array([0, 0, 1, 1])

In [12]:
a = 0.1
b = -17

In [13]:
H = a * X + b
H

array([-1.,  0.,  1.,  2.])

In [14]:
def sigmoid(H):
    return 1 / (1 + e**(-H))

In [15]:
z = sigmoid(H)
z

array([0.26894142, 0.5       , 0.73105858, 0.88079708])

In [ ]:
# 비용(정답을 얼마나 잘맞췄는지에 따른 벌점) 계산. y가 1일때 -y*log(z), y가 0일때 -(1-y)*log(1-z). 낮으면 잘맞춘거임
costs = - (y * np.log(z) + (1 - y) * np.log(1 - z))
costs

array([0.31326169, 0.69314718, 0.31326169, 0.12692801])

In [18]:
mean_cost = np.mean(costs)
mean_cost

np.float64(0.36164964165984087)