In [1]:
import numpy as np
from math import e

In [ ]:
# 키를 보고 농구선수인지 예측
X = np.array([160, 170, 180, 190])
y = np.array([0, 0, 1, 1])

X, y

(array([160, 170, 180, 190]), array([0, 0, 1, 1]))

In [3]:
# 입력값 정규화
X_mean = np.mean(X)
X_std = np.std(X)

X_norm = (X - X_mean) / X_std
X_mean, X_std, X_norm

(np.float64(175.0),
 np.float64(11.180339887498949),
 array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079]))

In [4]:
#  가중치, 편향 초기값 설정
a = 0.1
b = 0.0

In [5]:
# sigmoid 함수 정의
def sigmoid(H):
    return 1 / (1 + e ** (-H))



In [6]:
# 학습 전 예측 확인
H = a * X_norm + b
z = sigmoid(H)
H, z

(array([-0.13416408, -0.04472136,  0.04472136,  0.13416408]),
 array([0.4665092 , 0.48882152, 0.51117848, 0.5334908 ]))

In [8]:
# Cost 계산. 예측이 얼마나 틀렸는지
# log(0)방지하기 위해 z 범위 제한
epsilon = 1e-7
z_safe = np.clip(z, epsilon, 1 - epsilon)

costs = - (y * np.log(z_safe) + (1 - y) * np.log(1 - z_safe))
mean_cost = np.mean(costs)
costs, mean_cost

(array([0.62831346, 0.67103648, 0.67103648, 0.62831346]),
 np.float64(0.6496749678557904))

In [9]:
# dC/da = (z - y) * X_norm
# dC/db = z - y
# grad_a = mean((z-y) * X_norm)
# grad_b = mean(z-y)
epochs = 1000
learning_rate = 0.1
for epoch in range(epochs):
    H = a * X_norm + b
    z = sigmoid(H)
    z_safe = np.clip(z, epsilon, 1 - epsilon)

    grad_a = np.mean((z - y) * X_norm)
    grad_b = np.mean(z - y)

    a -= learning_rate * grad_a
    b -= learning_rate * grad_b

    costs = - (y * np.log(z_safe) + (1 - y) * np.log(1 - z_safe))
    mean_cost = np.mean(costs)

    if epoch % 100 == 0 or epoch == epochs - 1:
        print(f'Epoch {epoch}, 평균 비용(Cost): {mean_cost:.6f}, a: {a}, b: {b}')

Epoch 0, 평균 비용(Cost): 0.649675, a: 0.14222477014437584, b: -2.7755575615628915e-18
Epoch 100, 평균 비용(Cost): 0.198225, a: 2.0691458779851915, b: -4.4408920985006276e-17
Epoch 200, 평균 비용(Cost): 0.133789, a: 2.8606337961325523, b: -7.702172233337027e-17
Epoch 300, 평균 비용(Cost): 0.104196, a: 3.4015117223499463, b: -7.077671781985369e-17
Epoch 400, 평균 비용(Cost): 0.086193, a: 3.824387813233572, b: -9.298117831235679e-17
Epoch 500, 평균 비용(Cost): 0.073786, a: 4.175775944887929, b: -9.020562075079387e-17
Epoch 600, 평균 비용(Cost): 0.064613, a: 4.47810138384445, b: -1.0443035325380374e-16
Epoch 700, 평균 비용(Cost): 0.057512, a: 4.744185974341348, b: -7.459310946700272e-17
Epoch 800, 평균 비용(Cost): 0.051834, a: 4.982180478097351, b: -4.6837533851373755e-17
Epoch 900, 평균 비용(Cost): 0.047181, a: 5.197651280800426, b: -2.879640970121495e-17
Epoch 999, 평균 비용(Cost): 0.043330, a: 5.39271192293186, b: -4.0939474033052625e-17


In [10]:
input_height = 185
input_norm = (input_height - X_mean) / X_std

H_input = a * input_norm + b
probability = sigmoid(H_input)

print(f'\n키가 {input_height}cm인 사람의 농구선수 확률: {probability:.4f}')
if probability >= 0.5:
    print('판별 결과 : 농구선수입니다.')
else:
    print('판별 결과: 농구선수가 아닙니다.')


키가 185cm인 사람의 농구선수 확률: 0.9920
판별 결과 : 농구선수입니다.
